title: Test #0-01
author: parlousBlue
description: > # this means to ignore newlines until "baseurl:"
  Don't index this!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
